/*Add share id sequence and tag id sequence*/
use fddb;

INSERT INTO `fd_t_sequence` VALUES ('FD_SHARE_ID', 1, 1);
INSERT INTO `fd_t_sequence` VALUES ('FD_SHOP_IMAGE_ID', 1, 1);
INSERT INTO `fd_t_sequence` VALUES ('FD_TAG_ID', 1, 1);

/*Add table share*/
CREATE TABLE IF NOT EXISTS `fd_t_share` (
  `share_id` BIGINT(20) NOT NULL ,
  `user_id` BIGINT(20) NOT NULL ,
  `tags` VARCHAR(256) DEFAULT '',
  `up_count` INT(11) DEFAULT 0,
  `comment_count` INT(11) DEFAULT 0,
  `brower_count` INT(11) DEFAULT 0,
  `transfer_count` INT(11) DEFAULT 0,
  `content` TEXT,
  `hotness` DECIMAL(12,2) DEFAULT 0.0,
  `city_id` INT(11) DEFAULT NULL,
  `status` INT(3) DEFAULT 0, 
  `res1` INT(11) DEFAULT NULL,
  `res2` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`share_id`, `user_id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Add table share related shop*/
CREATE TABLE IF NOT EXISTS `fd_t_sharerelatedshop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `share_id` BIGINT(20) NOT NULL ,
  `shop_id` BIGINT(20),  
  `shop_name` VARCHAR(256),
  `shop_address` VARCHAR(256),
  PRIMARY KEY (`id`, `share_id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`share_id`)
(
	PARTITION p0 VALUES LESS THAN (100000),
	PARTITION p1 VALUES LESS THAN (200000),
	PARTITION p2 VALUES LESS THAN (300000),
	PARTITION p3 VALUES LESS THAN (400000),
	PARTITION p4 VALUES LESS THAN (500000),
	PARTITION p5 VALUES LESS THAN (600000),
	PARTITION p6 VALUES LESS THAN (700000),
	PARTITION p7 VALUES LESS THAN (800000),
	PARTITION p8 VALUES LESS THAN (900000),
	PARTITION p9 VALUES LESS THAN (1000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Add table share up*/
CREATE TABLE IF NOT EXISTS `fd_t_shareup` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `share_id` BIGINT(20) NOT NULL ,
  `user_id` BIGINT(20),  
  `up_time` DATETIME,
  PRIMARY KEY (`id`, `share_id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`share_id`)
(
	PARTITION p0 VALUES LESS THAN (100000),
	PARTITION p1 VALUES LESS THAN (200000),
	PARTITION p2 VALUES LESS THAN (300000),
	PARTITION p3 VALUES LESS THAN (400000),
	PARTITION p4 VALUES LESS THAN (500000),
	PARTITION p5 VALUES LESS THAN (600000),
	PARTITION p6 VALUES LESS THAN (700000),
	PARTITION p7 VALUES LESS THAN (800000),
	PARTITION p8 VALUES LESS THAN (900000),
	PARTITION p9 VALUES LESS THAN (1000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Add table share comment*/
CREATE TABLE IF NOT EXISTS `fd_t_sharecomment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `share_id` BIGINT(20) NOT NULL ,
  `from_user_id` BIGINT(20),  
  `to_user_id` BIGINT(20),  
  `comment_time` DATETIME,
  PRIMARY KEY (`id`, `share_id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`share_id`)
(
	PARTITION p0 VALUES LESS THAN (100000),
	PARTITION p1 VALUES LESS THAN (200000),
	PARTITION p2 VALUES LESS THAN (300000),
	PARTITION p3 VALUES LESS THAN (400000),
	PARTITION p4 VALUES LESS THAN (500000),
	PARTITION p5 VALUES LESS THAN (600000),
	PARTITION p6 VALUES LESS THAN (700000),
	PARTITION p7 VALUES LESS THAN (800000),
	PARTITION p8 VALUES LESS THAN (900000),
	PARTITION p9 VALUES LESS THAN (1000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Add table best share*/
CREATE TABLE IF NOT EXISTS `fd_t_bestshare` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `year` INT(11),  
  `month` INT(11),  
  `share_id` BIGINT(20),
  `gift_id` INT(11),  
   PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Add table gift*/
CREATE TABLE IF NOT EXISTS `fd_t_gift` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256),  
  `price` DECIMAL(12, 2),  
  `pic_list`  TEXT,
  `status` INT(3),  
  `count` INT(11), 
   PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Add table tag*/
CREATE TABLE IF NOT EXISTS `fd_t_tag` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(64),  
  `user_id` BIGINT(20),  
  `num` BIGINT(20), 
  `hotness` DECIMAL(12, 2), 
   PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Add table shop tag*/
CREATE TABLE IF NOT EXISTS `fd_t_shoptag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `shop_id` BIGINT(20),
  `tag_id` INT(11),
  `tag_name` VARCHAR(64),  
  `tag_num` INT(11),  
  `user_id_list` TEXT, 
   PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;