# encoding:utf-8
from copy import deepcopy
import os.path
import logging

from ndict import ndict


PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))

# New
CONFIG = ndict()
CONFIG.NAME = 'DEFAULT_CONFIG'
CONFIG.DEBUG = True
CONFIG.TESTING = False
CONFIG.PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))

CONFIG.LOGGER = ndict()
CONFIG.LOGGER.LEVEL = logging.DEBUG
CONFIG.LOGGER.FORMAT = '%(asctime)s %(filename)s[%(lineno)d] %(name)s: %(message)s'
CONFIG.LOGGER.OUTPUT_DIRECTORY = os.path.join(PROJECT_PATH, 'output')

CONFIG.REDIS = ndict()
CONFIG.REDIS.HOST = '115.28.143.67'
CONFIG.REDIS.PASSWORD = 'impower2015'

CONFIG.RABBITMQ = ndict()
CONFIG.RABBITMQ.USER = 'fd'
CONFIG.RABBITMQ.PASSWD = 'fd2015'

CONFIG.TORNADO = ndict()
CONFIG.TORNADO.PORT = '8887'
CONFIG.TORNADO.SETTINGS = dict(
    template_path=os.path.join(os.path.dirname(__file__), "templates/"),
    static_path=os.path.join(os.path.dirname(__file__), "static/"),
    debug=CONFIG.DEBUG,
    cookie_secret="13skss9845fui2345hsz846fdah848",
    login_url="/login",
)

CONFIG.MYSQL = ndict()
CONFIG.MYSQL.PORT = 3306
CONFIG.MYSQL.HOST = '115.28.143.67'
CONFIG.MYSQL.USER = 'fd'
CONFIG.MYSQL.PASSWD = 'poweroverming'
CONFIG.MYSQL.DATABASE = 'fddb'

CONFIG.SQLALCHEMY = ndict()
CONFIG.SQLALCHEMY.URL = 'mysql://%s:%s@%s:%s/fddb?charset=utf8' % (
    CONFIG.MYSQL.USER, CONFIG.MYSQL.PASSWD, CONFIG.MYSQL.HOST, CONFIG.MYSQL.PORT)
CONFIG.SQLALCHEMY.SETTINGS = dict(
    encoding='utf-8',
    echo=False,
    pool_size=50,
    max_overflow=10,
)

CONFIG.MONGO = ndict()
CONFIG.MONGO.HOST = '115.28.143.67'
CONFIG.MONGO.PORT = 27017

CONFIG.THIRDLOGIN = ndict()
CONFIG.THIRDLOGIN.QQ_APP_KEY = '101243441'
CONFIG.THIRDLOGIN.WEIBO_APP_KEY = '4112213288'
CONFIG.THIRDLOGIN.WEIBO_APP_SECRET = 'b28cfb7af7688cf8437a6bb7569d1342'
CONFIG.THIRDLOGIN.WECHAT_APP_KEY = 'wxe4a8a76947f4d2af'
CONFIG.THIRDLOGIN.WECHAT_APP_SECRET = '2a294082cadc4980198e679200008c8e'

CONFIG.CK_DOCUMENT_DOMAIN = '115.28.143.67'

CONFIG.AUTH_URL = 'http://115.28.143.67:8887/auth'
CONFIG.AUTH_SERVER = 'http://115.28.143.67:8887'

CONFIG.FD_CHAT_SERVER = 'http://115.28.143.67:8889'

CONFIG.DEFAULT_PORTRAIT_URL = '46804488224a8bca3220b9d41b87be10.png'

CONFIG.MODULES = ndict()
CONFIG.MODULES.AUTH = 1
CONFIG.MODULES.USER = 1
CONFIG.MODULES.CHAT = 0
CONFIG.MODULES.MT = 1

DEVELOPMENT_CONFIG = deepcopy(CONFIG)
DEVELOPMENT_CONFIG.NAME = 'DEVELOPMENT_CONFIG'

TESTING_CONFIG = deepcopy(CONFIG)
TESTING_CONFIG.NAME = 'TESTING_CONFIG'
TESTING_CONFIG.TESTING = True

PRODUCTION_CONFIG = deepcopy(CONFIG)
PRODUCTION_CONFIG.NAME = 'PRODUCTION_CONFIG'
PRODUCTION_CONFIG.DEBUG = False
PRODUCTION_CONFIG.TESTING = False

PRODUCTION_CONFIG.LOGGER.OUTPUT_DIRECTORY = '/data/log'

PRODUCTION_CONFIG.REDIS.HOST = 'localhost'
PRODUCTION_CONFIG.REDIS.PASSWORD = 'BJYP@2015_redis'

PRODUCTION_CONFIG.MYSQL.HOST = '127.0.0.1'
PRODUCTION_CONFIG.MYSQL.USER = 'fd'
PRODUCTION_CONFIG.MYSQL.PASSWD = 'bEijingyinpu_2015'
PRODUCTION_CONFIG.MYSQL.DATABASE = 'fddb'

PRODUCTION_CONFIG.SQLALCHEMY.URL = 'mysql://%s:%s@%s:%s/fddb?charset=utf8' % (
    PRODUCTION_CONFIG.MYSQL.USER, PRODUCTION_CONFIG.MYSQL.PASSWD, PRODUCTION_CONFIG.MYSQL.HOST,
    PRODUCTION_CONFIG.MYSQL.PORT)

PRODUCTION_CONFIG.AUTH_SERVER = 'http://127.0.0.1:8887'
PRODUCTION_CONFIG.AUTH_URL = 'http://127.0.0.1:8887/auth'
PRODUCTION_CONFIG.FD_CHAT_SERVER = 'http://127.0.0.1:8889'

PRODUCTION_CONFIG.CK_DOCUMENT_DOMAIN = 'immbear.com'

PRODUCTION_CONFIG.MONGO.HOST = 'mongodb://shopaddress:shopaddress123@112.124.115.140:27017/shop_address'

PRODUCTION_CONFIG.MODULES.AUTH = 1
PRODUCTION_CONFIG.MODULES.USER = 1
PRODUCTION_CONFIG.MODULES.CHAT = 0
PRODUCTION_CONFIG.MODULES.MT = 1

CHAT_PRODUCTION_CONFIG = deepcopy(PRODUCTION_CONFIG)
CHAT_PRODUCTION_CONFIG.NAME = 'CHAT_PRODUCTION_CONFIG'
CHAT_PRODUCTION_CONFIG.TORNADO.PORT = '8889'

CHAT_PRODUCTION_CONFIG.MODULES.AUTH = 0
CHAT_PRODUCTION_CONFIG.MODULES.USER = 0
CHAT_PRODUCTION_CONFIG.MODULES.CHAT = 1
CHAT_PRODUCTION_CONFIG.MODULES.MT = 0

CONFIG = DEVELOPMENT_CONFIG