/**********************************************************
Create table for forward database
**********************************************************/
use fddb;

/*Table 1*/
CREATE TABLE IF NOT EXISTS `fd_t_sequence` (
  `sequence_name` VARCHAR(64) NOT NULL,
  `current_value` BIGINT(20) NOT NULL,
  `increment_value` INT(11) NOT NULL default '1',
  PRIMARY KEY  (`sequence_name`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 2*/
CREATE TABLE IF NOT EXISTS `fd_t_thmbankaccount`(
  `account_type` INT(11) NOT NULL,
  `bank_account` VARCHAR(64) NOT NULL,
  `bank_name` VARCHAR(64) ,
  `account_holder` VARCHAR(64) ,
  PRIMARY KEY (`account_type`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 3*/
CREATE TABLE IF NOT EXISTS `fd_t_category`(
  `id` INT(11) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `parent_id` INT(11) ,
  `cate_line` TEXT ,
  `cate_pic` VARCHAR(512) ,
  PRIMARY KEY (`id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 4*/
CREATE TABLE IF NOT EXISTS `fd_t_shop`(
  `shop_id` BIGINT(20) NOT NULL,
  `brand_name` VARCHAR(64) ,
  `shop_name` VARCHAR(256) NOT NULL,
  `qrcode` VARCHAR(256) ,
  `business_hours` VARCHAR(64) ,  
  `telephone_no` VARCHAR(64) ,
  `city_id` INT(11) ,
  `district_id` INT(11) ,
  `business_area` VARCHAR(64) ,
  `address` VARCHAR(256) ,
  `longitude` DECIMAL(10,6) ,
  `latitude` DECIMAL(10,6) ,
  `pic_url_list` TEXT ,
  `category_list` TEXT ,
  `introduction` TEXT ,
  `status` INT(3) ,
  PRIMARY KEY (`shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 5*/
CREATE TABLE IF NOT EXISTS `fd_t_shopaccount`(
  `shop_id` BIGINT(20) NOT NULL,
  `portrait_url` VARCHAR(512) ,
  `contact_name` VARCHAR(64) ,
  `contact_phone_no` VARCHAR(32) , 
  `contact_email` VARCHAR(128) ,
  `contact_qq` VARCHAR(64) ,
  `service_balance` DECIMAL(12,2) ,
  `service_deadline` DATETIME ,
  `service_status` INT(3) , 
  PRIMARY KEY (`shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 6*/
CREATE TABLE IF NOT EXISTS `fd_t_shopchargedetail`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `swift_num` BIGINT(20) NOT NULL,
  `shop_id` BIGINT(20) NOT NULL,
  `type` INT(3) ,
  `time` DATETIME ,
  `income` DECIMAL(12,2) ,
  `expense` DECIMAL(12,2) ,
  `balance` DECIMAL(12,2) ,
  `remark` TEXT ,
  `detail` TEXT ,
  PRIMARY KEY (`id`,`shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`shop_id`)
(
	PARTITION p0 VALUES LESS THAN (10000),
	PARTITION p1 VALUES LESS THAN (20000),
	PARTITION p2 VALUES LESS THAN (30000),
	PARTITION p3 VALUES LESS THAN (40000),
	PARTITION p4 VALUES LESS THAN (50000),
	PARTITION p5 VALUES LESS THAN (60000),
	PARTITION p6 VALUES LESS THAN (70000),
	PARTITION p7 VALUES LESS THAN (80000),
	PARTITION p8 VALUES LESS THAN (90000),
	PARTITION p9 VALUES LESS THAN (100000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 7*/
CREATE TABLE IF NOT EXISTS `fd_t_user`(
  `user_id` BIGINT(20) NOT NULL ,
  `name` VARCHAR(32) ,
  `gender` INT(3) ,
  `birthday` DATE ,
  `mcode` VARCHAR(32) ,
  `qrcode` VARCHAR(256) ,
  `phone_no` VARCHAR(32) ,
  `email` VARCHAR(256) ,
  `portrait_url` VARCHAR(512) ,
  `city_id` INT(11) ,
  PRIMARY KEY (`user_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 8*/
CREATE TABLE IF NOT EXISTS `fd_t_account`(
  `acc_id` BIGINT(20) NOT NULL ,
  `acc_type` INT(3) ,
  `auth_mode` INT(3) ,
  `account` VARCHAR(64),
  `phone_no` VARCHAR(32) ,
  `email` VARCHAR(256) ,  
  `password` VARCHAR(64),
  `open_id` VARCHAR(512) ,  
  `register_time` DATETIME ,
  PRIMARY KEY (`acc_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`acc_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 9*/
CREATE TABLE IF NOT EXISTS `fd_t_useraddress`(
  `id` BIGINT(20) NOT NULL ,
  `user_id` BIGINT(20) NOT NULL ,
  `name` VARCHAR(64) ,
  `phone_no` VARCHAR(32) , 
  `province_id` INT(11) , 
  `city_id` INT(11) , 
  `address` VARCHAR(512) ,
  `postcode` VARCHAR(32) ,
  `default` INT(3) ,
  PRIMARY KEY (`id`, `user_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 10*/
CREATE TABLE IF NOT EXISTS `fd_t_goods`(
  `goods_id` BIGINT(20) NOT NULL,
  `category_list` TEXT ,
  `description` VARCHAR(256) ,
  `detail` TEXT ,
  `bar_code` VARCHAR(256) ,
  `price` DECIMAL(12,2) ,
  `promotion_price` DECIMAL(12,2) ,
  `pic_url_list` TEXT ,
  `brand_name` VARCHAR(64) ,
  `basic_info` TEXT ,
  `remark` TEXT ,
  `shop_id` BIGINT(20) ,
  `publish_time` DATETIME ,
  `status` INT(3) ,
  `target` TEXT ,
  PRIMARY KEY (`goods_id`, `shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`shop_id`)
(
	PARTITION p0 VALUES LESS THAN (10000),
	PARTITION p1 VALUES LESS THAN (20000),
	PARTITION p2 VALUES LESS THAN (30000),
	PARTITION p3 VALUES LESS THAN (40000),
	PARTITION p4 VALUES LESS THAN (50000),
	PARTITION p5 VALUES LESS THAN (60000),
	PARTITION p6 VALUES LESS THAN (70000),
	PARTITION p7 VALUES LESS THAN (80000),
	PARTITION p8 VALUES LESS THAN (90000),
	PARTITION p9 VALUES LESS THAN (100000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 11*/
CREATE TABLE IF NOT EXISTS `fd_t_goodsstandard`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `goods_id` BIGINT(20) NOT NULL,
  `stand_key` TEXT ,
  `is_price_decider` INT(3) ,
  `stand_value` TEXT ,
  `price` DECIMAL(12,2) ,
  `promotion_price` DECIMAL(12,2) ,
  PRIMARY KEY (`id`, `goods_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`goods_id`)
(
	PARTITION p0 VALUES LESS THAN (100000),
	PARTITION p1 VALUES LESS THAN (200000),
	PARTITION p2 VALUES LESS THAN (300000),
	PARTITION p3 VALUES LESS THAN (400000),
	PARTITION p4 VALUES LESS THAN (500000),
	PARTITION p5 VALUES LESS THAN (600000),
	PARTITION p6 VALUES LESS THAN (700000),
	PARTITION p7 VALUES LESS THAN (800000),
	PARTITION p8 VALUES LESS THAN (900000),
	PARTITION p9 VALUES LESS THAN (1000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 12*/
CREATE TABLE IF NOT EXISTS `fd_t_fitting`(
  `goods_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `pic_url` VARCHAR(512),
  `fit_time` DATETIME,
  `description` TEXT
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 13*/
CREATE TABLE IF NOT EXISTS `fd_t_activity`(
  `act_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `act_title` VARCHAR(256),
  `act_content` TEXT ,
  `begin_time` DATETIME ,
  `end_time` DATETIME ,
  `shop_id` BIGINT(20) ,
  `publish_time` DATETIME ,
  PRIMARY KEY (`act_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 14*/
CREATE TABLE IF NOT EXISTS `fd_t_recommend`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `city_id` INT(11) ,
  `shop_id` BIGINT(20) ,
  `declaration` TEXT ,
  `begin_time` DATETIME ,
  `end_time` DATETIME ,
  `status` INT(3) ,
  PRIMARY KEY (`id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 15*/
CREATE TABLE IF NOT EXISTS `fd_t_phoneauth`(
  `phone_no` VARCHAR(32) NOT NULL,
  `auth_code` INT(11) ,
  `auth_deadline` DATETIME ,
  PRIMARY KEY (`phone_no`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 16*/
CREATE TABLE IF NOT EXISTS `fd_t_favorite`(
  `user_id` BIGINT(20) NOT NULL,
  `goods_id` BIGINT(20) ,
  `save_time` DATETIME 
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 17*/
CREATE TABLE IF NOT EXISTS `fd_t_fans`(
  `user_id` BIGINT(20) NOT NULL,
  `shop_id` BIGINT(20) ,
  `join_time` DATETIME ,
  `push_message_enable` INT(3) ,
  PRIMARY KEY (`user_id`, `shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 18*/
CREATE TABLE IF NOT EXISTS `fd_t_visitedshop`(
  `user_id` BIGINT(20) NOT NULL,
  `shop_id` BIGINT(20) ,
  `visit_count` INT(10) ,
  `last_visit_time` DATETIME 
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 19*/
CREATE TABLE IF NOT EXISTS `fd_t_friend`(
  `user_id` BIGINT(20) NOT NULL,
  `friend_id` BIGINT(20) ,
  `friend_name` VARCHAR(32) ,
  PRIMARY KEY (`user_id`, `friend_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 20*/
CREATE TABLE IF NOT EXISTS `fd_t_privatesetting`(
  `user_id` BIGINT(20) NOT NULL,
  `save_enable` INT(3) ,
  `fans_enable` INT(3) ,
  `visit_enable` INT(3) ,
  PRIMARY KEY (`user_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 21*/
CREATE TABLE IF NOT EXISTS `fd_t_fansmessage`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `shop_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `message` TEXT ,
  `push_time` DATETIME ,
  PRIMARY KEY (`id`, `shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`shop_id`)
(
	PARTITION p0 VALUES LESS THAN (10000),
	PARTITION p1 VALUES LESS THAN (20000),
	PARTITION p2 VALUES LESS THAN (30000),
	PARTITION p3 VALUES LESS THAN (40000),
	PARTITION p4 VALUES LESS THAN (50000),
	PARTITION p5 VALUES LESS THAN (60000),
	PARTITION p6 VALUES LESS THAN (70000),
	PARTITION p7 VALUES LESS THAN (80000),
	PARTITION p8 VALUES LESS THAN (90000),
	PARTITION p9 VALUES LESS THAN (100000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 22*/
CREATE TABLE IF NOT EXISTS `fd_t_forum`(
  `forum_id` VARCHAR(256) NOT NULL,
  `forum_name` VARCHAR(32),
  `forum_pic` VARCHAR(512),
  `user_id` BIGINT(20) ,
  `is_initiator` INT(3) ,
  `join_time` DATETIME 
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 23*/
CREATE TABLE IF NOT EXISTS `fd_t_feedback`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `direction` INT(3) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `content` TEXT ,
  `time` DATETIME ,
  PRIMARY KEY (`id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 24*/
CREATE TABLE IF NOT EXISTS `fd_t_appversion`(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `system` INT(3) ,
  `version` VARCHAR(64) ,
  `time` DATETIME ,
  `remark` TEXT ,
  `packet` VARCHAR(512) ,
  PRIMARY KEY (`id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 25*/
CREATE TABLE IF NOT EXISTS `fd_t_citycode`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `city_id` INT(11) NOT NULL ,
  `city_name` VARCHAR(64) ,
  `district_id` INT(11) ,
  `district_name` VARCHAR(64) ,
  `province_id` INT(11) ,
  `province_name` VARCHAR(64) ,
  `country_id` INT(11) ,
  `country_name` VARCHAR(64) ,
  `is_support` INT(3) ,
  PRIMARY KEY (`id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 26*/
CREATE TABLE IF NOT EXISTS `fd_t_companyinfo`(
  `name` VARCHAR(64) ,
  `phone_no_list` VARCHAR(512),
  `email` VARCHAR(64), 
  `introduction` TEXT,
  `disclaimer` TEXT
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 27*/
CREATE TABLE IF NOT EXISTS `fd_t_userlogindevice`(
  `user_id` BIGINT(20) NOT NULL,
  `device` VARCHAR(256) ,
  `login_time` DATETIME ,
  PRIMARY KEY (`user_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 28*/
CREATE TABLE IF NOT EXISTS `fd_t_systemmessage`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `message` INT(3) ,
  `push_message` INT(3) ,
  PRIMARY KEY (`id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 29*/
CREATE TABLE IF NOT EXISTS `fd_t_visitshoprecord`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `shop_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `action` INT(3) ,
  `time` DATETIME ,
  PRIMARY KEY (`id`, `shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`shop_id`)
(
	PARTITION p0 VALUES LESS THAN (10000),
	PARTITION p1 VALUES LESS THAN (20000),
	PARTITION p2 VALUES LESS THAN (30000),
	PARTITION p3 VALUES LESS THAN (40000),
	PARTITION p4 VALUES LESS THAN (50000),
	PARTITION p5 VALUES LESS THAN (60000),
	PARTITION p6 VALUES LESS THAN (70000),
	PARTITION p7 VALUES LESS THAN (80000),
	PARTITION p8 VALUES LESS THAN (90000),
	PARTITION p9 VALUES LESS THAN (100000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 30*/
CREATE TABLE IF NOT EXISTS `fd_t_fansmessageconfig`(
  `shop_id` BIGINT(20) NOT NULL ,
  `current_p2p_count` INT(11) ,
  `p2p_remain_count` INT(11) ,
  `next_p2p_count` INT(11) ,
  `current_mass_count` INT(11) ,
  `mass_remain_count` INT(11) ,
  `next_mass_count` INT(11) ,
  PRIMARY KEY (`shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 31*/
CREATE TABLE IF NOT EXISTS `fd_t_fansmessagecharge`(
  `id` INT(11) NOT NULL ,
  `type` INT(3) ,
  `count` INT(11) ,
  `money` DECIMAL(12,2) ,
  PRIMARY KEY (`id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 32*/
CREATE TABLE IF NOT EXISTS `fd_t_joinshop`(
  `shop_id` BIGINT(20) NOT NULL,
  `shop_name` VARCHAR(256) NOT NULL,
  `pic_url` TEXT ,
  PRIMARY KEY (`shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 33*/
CREATE TABLE IF NOT EXISTS `fd_t_goodsinfo`(
  `goods_id` BIGINT(20) NOT NULL ,
  `sales_volume` INT(11) ,
  `browse_count` INT(11) ,
  `attention_count` INT(11) ,
  `stock_count` INT(11) ,
  `res1` INT(3),
  `res2` INT(3),
  `res3` TEXT,
  PRIMARY KEY (`goods_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`goods_id`)
(
	PARTITION p0 VALUES LESS THAN (500000),
	PARTITION p1 VALUES LESS THAN (1000000),
	PARTITION p2 VALUES LESS THAN (1500000),
	PARTITION p3 VALUES LESS THAN (2000000),
	PARTITION p4 VALUES LESS THAN (2500000),
	PARTITION p5 VALUES LESS THAN (3000000),
	PARTITION p6 VALUES LESS THAN (3500000),
	PARTITION p7 VALUES LESS THAN (4000000),
	PARTITION p8 VALUES LESS THAN (4500000),
	PARTITION p9 VALUES LESS THAN (5000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);


/*Table 34*/
CREATE TABLE IF NOT EXISTS `fd_t_bill_201501`(
  `bill_no` BIGINT(20) NOT NULL ,  
  `bill_status` INT(3) NOT NULL ,
  `user_id` BIGINT(20) ,
  `shop_id` BIGINT(20) ,
  `bill_password` VARCHAR(64) ,
  `phone_no` VARCHAR(32) ,
  `bill_time` DATETIME ,  
  `goods_id` BIGINT(20) ,
  `goods_price` DECIMAL(12,2) ,
  `goods_count` INT(11) ,
  `goods_standard` TEXT , 
  `bill_amount` DECIMAL(12,2) , 
  `pay_mode` TEXT ,  
  `time_info` TEXT ,
  `res1` INT(11) ,
  `res2` TEXT ,
  PRIMARY KEY (`bill_no`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 35*/
CREATE TABLE IF NOT EXISTS `fd_t_userbill_1`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT, 
  `user_id` BIGINT(20) NOT NULL ,
  `bill_no` BIGINT(20) NOT NULL ,  
  `bill_status` INT(3) NOT NULL ,  
  `flag` INT(3) NOT NULL ,  
  PRIMARY KEY (`id`, `user_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 36*/
CREATE TABLE IF NOT EXISTS `fd_t_shopbill_1`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT, 
  `shop_id` BIGINT(20) NOT NULL ,
  `bill_no` BIGINT(20) NOT NULL ,  
  `bill_status` INT(3) NOT NULL , 
  `flag` INT(3) NOT NULL ,    
  PRIMARY KEY (`id`, `shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 37*/
CREATE TABLE IF NOT EXISTS `fd_t_commission`(
  `shop_id` BIGINT(20) NOT NULL ,
  `mode` INT(3) NOT NULL ,  
  `money` DECIMAL(12,2) ,  
  `rate` DECIMAL(5,4) , 
  PRIMARY KEY (`shop_id`)
) ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 38*/
CREATE TABLE IF NOT EXISTS `fd_t_match` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `city_id` INT(11) DEFAULT NULL,
  `gender` INT(11) DEFAULT NULL,
  `age_min` INT(11) DEFAULT NULL,
  `age_max` INT(11) DEFAULT NULL,
  `spare0` VARCHAR(256) DEFAULT NULL,
  `spare1` VARCHAR(256) DEFAULT NULL,
  `spare2` VARCHAR(256) DEFAULT NULL,
  `spare3` VARCHAR(256) DEFAULT NULL,
  `spare4` VARCHAR(256) DEFAULT NULL,
  `spare5` VARCHAR(256) DEFAULT NULL,
  `spare6` VARCHAR(256) DEFAULT NULL,
  `spare7` VARCHAR(256) DEFAULT NULL,
  `user_id` BIGINT(20) DEFAULT NULL,
  `status` INT(11) DEFAULT NULL,
  `time_limit` INT(11) DEFAULT NULL,
  `des` TEXT,
  PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 39*/
CREATE TABLE IF NOT EXISTS `fd_t_share` (
  `share_id` BIGINT(20) NOT NULL ,
  `user_id` BIGINT(20) NOT NULL ,
  `tags` VARCHAR(256) DEFAULT '',
  `up_count` INT(11) DEFAULT 0,
  `comment_count` INT(11) DEFAULT 0,
  `brower_count` INT(11) DEFAULT 0,
  `transfer_count` INT(11) DEFAULT 0,
  `content` TEXT DEFAULT '',
  `hotness` DECIMAL(12,2) DEFAULT 0.0,
  `city_id` INT(11) DEFAULT NULL,
  `status` INT(3) DEFAULT 0, 
  `res1` INT(11) DEFAULT NULL,
  `res2` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`share_id`, `user_id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`user_id`)
(
	PARTITION p0 VALUES LESS THAN (1000000),
	PARTITION p1 VALUES LESS THAN (2000000),
	PARTITION p2 VALUES LESS THAN (3000000),
	PARTITION p3 VALUES LESS THAN (4000000),
	PARTITION p4 VALUES LESS THAN (5000000),
	PARTITION p5 VALUES LESS THAN (6000000),
	PARTITION p6 VALUES LESS THAN (7000000),
	PARTITION p7 VALUES LESS THAN (8000000),
	PARTITION p8 VALUES LESS THAN (9000000),
	PARTITION p9 VALUES LESS THAN (10000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 40*/
CREATE TABLE IF NOT EXISTS `fd_t_sharerelatedshop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `share_id` BIGINT(20) NOT NULL ,
  `shop_id` BIGINT(20),  
  `shop_name` VARCHAR(256),
  `shop_address` VARCHAR(256),
  PRIMARY KEY (`id`, `share_id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`share_id`)
(
	PARTITION p0 VALUES LESS THAN (100000),
	PARTITION p1 VALUES LESS THAN (200000),
	PARTITION p2 VALUES LESS THAN (300000),
	PARTITION p3 VALUES LESS THAN (400000),
	PARTITION p4 VALUES LESS THAN (500000),
	PARTITION p5 VALUES LESS THAN (600000),
	PARTITION p6 VALUES LESS THAN (700000),
	PARTITION p7 VALUES LESS THAN (800000),
	PARTITION p8 VALUES LESS THAN (900000),
	PARTITION p9 VALUES LESS THAN (1000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 41*/
CREATE TABLE IF NOT EXISTS `fd_t_shareup` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `share_id` BIGINT(20) NOT NULL ,
  `user_id` BIGINT(20),  
  `up_time` DATETIME,
  PRIMARY KEY (`id`, `share_id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`share_id`)
(
	PARTITION p0 VALUES LESS THAN (100000),
	PARTITION p1 VALUES LESS THAN (200000),
	PARTITION p2 VALUES LESS THAN (300000),
	PARTITION p3 VALUES LESS THAN (400000),
	PARTITION p4 VALUES LESS THAN (500000),
	PARTITION p5 VALUES LESS THAN (600000),
	PARTITION p6 VALUES LESS THAN (700000),
	PARTITION p7 VALUES LESS THAN (800000),
	PARTITION p8 VALUES LESS THAN (900000),
	PARTITION p9 VALUES LESS THAN (1000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 42*/
CREATE TABLE IF NOT EXISTS `fd_t_sharecomment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `share_id` BIGINT(20) NOT NULL ,
  `from_user_id` BIGINT(20),  
  `to_user_id` BIGINT(20),  
  `comment_time` DATETIME,
  PRIMARY KEY (`id`, `share_id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci
PARTITION BY RANGE(`share_id`)
(
	PARTITION p0 VALUES LESS THAN (100000),
	PARTITION p1 VALUES LESS THAN (200000),
	PARTITION p2 VALUES LESS THAN (300000),
	PARTITION p3 VALUES LESS THAN (400000),
	PARTITION p4 VALUES LESS THAN (500000),
	PARTITION p5 VALUES LESS THAN (600000),
	PARTITION p6 VALUES LESS THAN (700000),
	PARTITION p7 VALUES LESS THAN (800000),
	PARTITION p8 VALUES LESS THAN (900000),
	PARTITION p9 VALUES LESS THAN (1000000),
	PARTITION pm VALUES LESS THAN MAXVALUE	
);

/*Table 43*/
CREATE TABLE IF NOT EXISTS `fd_t_bestshare` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `year` INT(11),  
  `month` INT(11),  
  `share_id` BIGINT(20),
  `gift_id` INT(11),  
   PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 44*/
CREATE TABLE IF NOT EXISTS `fd_t_gift` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256),  
  `price` DECIMAL(12, 2),  
  `pic_list`  TEXT,
  `status` INT(3),  
  `count` INT(11), 
   PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 45*/
CREATE TABLE IF NOT EXISTS `fd_t_tag` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(64),  
  `user_id` BIGINT(20),  
  `num` BIGINT(20), 
  `hotness` DECIMAL(12, 2), 
   PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;

/*Table 46*/
CREATE TABLE IF NOT EXISTS `fd_t_shoptag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `shop_id` BIGINT(20),
  `tag_id` INT(11),
  `tag_name` VARCHAR(64),  
  `tag_num` INT(11),  
  `user_id_list` TEXT, 
   PRIMARY KEY (`id`)
) ENGINE=INNODB 
CHARACTER SET utf8
COLLATE utf8_general_ci;



