#-*- coding:utf-8 -*-
"""
Domain name
"""
FD_DOMAIN_NAME = "http://www.immbear.com"

"""
Account type define
"""
FD_ACCOUNT_TYPE_MMX_TEAM = 1
FD_ACCOUNT_TYPE_ROOT = 2
FD_ACCOUNT_TYPE_ADMINISTRATOR = 3
FD_ACCOUNT_TYPE_USER = 4
FD_ACCOUNT_TYPE_MERCHANT = 5
FD_ACCOUNT_TYPE_OPERATION = 6
FD_ACCOUNT_TYPE_CUSTOMER_SERVICE = 7
FD_ACCOUNT_TYPE_MARKET = 8
FD_ACCOUNT_TYPE_CHAT_MAN = 9
FD_ACCOUNT_TYPE_VIRTUAL_USER = 10
FD_ACCOUNT_TYPE_VIRTUAL_MERCHANT = 11

"""
Authenticate mode define
"""
FD_AUTH_MODE_ACCOUNT = 1
FD_AUTH_MODE_PHONE = 2
FD_AUTH_MODE_EMAIL = 3
FD_AUTH_MODE_QQ = 4
FD_AUTH_MODE_WECHAT = 5
FD_AUTH_MODE_WEIBO = 6
FD_AUTH_MODE_ALIPAY = 7

"""
Personal information attribution define
"""
FD_PERSONAL_INFO_NAME = 1
FD_PERSONAL_INFO_PORTRAIT = 2
FD_PERSONAL_INFO_GENDER = 3
FD_PERSONAL_INFO_CITY = 4

"""
Gender define
"""
FD_GENDER_MAN = 1
FD_GENDER_WOMEN = 2

"""
Define bank account type
"""
FD_BANK_ACCOUNT_TYPE_ABC = 1 
FD_BANK_ACCOUNT_TYPE_ICBC = 2
FD_BANK_ACCOUNT_TYPE_CCB = 3
FD_BANK_ACCOUNT_TYPE_CB = 4
FD_BANK_ACCOUNT_TYPE_CMD = 5
FD_BANK_ACCOUNT_TYPE_BOC = 6
FD_BANK_ACCOUNT_TYPE_ALI = 7
FD_BANK_ACCOUNT_TYPE_WECHAT = 8


'''
image and other resource url prefix
'''
MMX_IMG_BUCKET = "mmx-img-public"
OSS_URL_PRIFIX  = 'http://img.immbear.com/'
